const { test, expect } = require("@playwright/test")

test("login rejects bad credentials, returns to requested page, and logout protects it again", async ({ page }) => {
  await page.goto("/clients")
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole("heading", { name: "Welcome back." })).toBeVisible()
  await expect(page.getByRole("navigation", { name: "Main navigation" })).toHaveCount(0)
  await page.getByLabel("Username", { exact: true }).fill("admin")
  await page.getByLabel("Password", { exact: true }).fill("wrong")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page.getByRole("alert")).toContainText("username or password")
  await expect(page.getByLabel("Password", { exact: true })).toHaveValue("")
  await page.getByLabel("Password", { exact: true }).fill("studio-test-password")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page).toHaveURL(/\/clients$/)
  await page.getByRole("button", { name: "Sign out", exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.goto("/clients")
  await expect(page).toHaveURL(/\/login$/)
})

test("login fits a phone and an expired calendar frame returns to login", async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/login")
  await expect(page.getByRole("heading", { name: "Welcome back." })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByLabel("Username", { exact: true }).fill("admin")
  await page.getByLabel("Password", { exact: true }).fill("studio-test-password")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page.getByRole("link", { name: "Next day", exact: true })).toBeVisible()
  await context.clearCookies()
  await page.getByRole("link", { name: "Next day", exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByLabel("Username", { exact: true })).toBeVisible()
})
