const { test, expect } = require("./support/auth")

test("details stay on the calendar, trap focus, and close without losing position", async ({ page }) => {
  await page.goto("/?view=day&date=2030-01-07")
  const booking = page.locator(".appointment-card").filter({ hasText: "Existing Client" })
  const viewport = page.locator(".calendar-viewport")
  await viewport.evaluate(element => { element.scrollTop = 60 })
  const scrollTop = await viewport.evaluate(element => element.scrollTop)
  const calendarURL = page.url()
  await booking.click()
  const dialog = page.getByRole("dialog", { name: "Existing Client", exact: true })
  await expect(dialog).toBeVisible()
  await expect(page).toHaveURL(calendarURL)
  await expect(dialog).toContainText("Cut & finish")
  await expect(dialog).toContainText("60 minutes")
  await expect(dialog.getByRole("link", { name: "existing@example.com" })).toBeVisible()
  await expect(dialog.locator("input, select, textarea")).toHaveCount(0)
  await expect(dialog.getByRole("button", { name: "Close booking details" })).toBeFocused()
  await page.keyboard.press("Shift+Tab")
  await expect(dialog.getByRole("link", { name: "Edit appointment", exact: true })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(dialog.getByRole("button", { name: "Close booking details" })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(booking).toBeFocused()
  expect(await viewport.evaluate(element => element.scrollTop)).toBe(scrollTop)

  await booking.click()
  await expect(dialog).toBeVisible()
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(booking).toBeFocused()
  await booking.click()
  await dialog.getByRole("button", { name: "Done", exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await booking.click()
  await dialog.getByRole("button", { name: "Close booking details" }).click()
  await expect(dialog).toHaveCount(0)
})

test("edit is explicit and preserves the filtered week context", async ({ page }) => {
  await page.goto("/?view=week&week=2030-01-07")
  await page.getByRole("link", { name: "Alex", exact: true }).click()
  await expect(page).toHaveURL(/stylist_id=/)
  const calendarURL = page.url()
  await page.locator(".appointment-card").filter({ hasText: "Existing Client" }).click()
  await page.getByRole("dialog").getByRole("link", { name: "Edit appointment", exact: true }).click()
  await expect(page).toHaveURL(/\/appointments\/\d+\/edit\?/)
  await expect(page.getByLabel("Date & time")).toHaveValue("2030-01-07T10:00")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.style.overflow)).not.toBe("hidden")
  await page.getByRole("link", { name: "Back to the calendar" }).click()
  await expect(page).toHaveURL(calendarURL)
})

test("details work on mobile and as a direct page without JavaScript", async ({ page, browser }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/?view=day&date=2030-01-07")
  const card = page.locator(".appointment-card").filter({ hasText: "Existing Client" })
  const path = await card.getAttribute("href")
  await card.click()
  const dialog = page.getByRole("dialog")
  await expect(dialog).toBeVisible()
  const rect = await dialog.boundingBox()
  expect(rect.x).toBeGreaterThanOrEqual(0)
  expect(rect.x + rect.width).toBeLessThanOrEqual(390)
  expect(rect.y + rect.height).toBeLessThanOrEqual(844)
  await expect(dialog.getByRole("link", { name: "Edit appointment", exact: true })).toBeVisible()

  const context = await browser.newContext({ javaScriptEnabled: false, storageState: await page.context().storageState() })
  const directPage = await context.newPage()
  await directPage.goto(`http://127.0.0.1:3100${path}`)
  await expect(directPage.getByRole("heading", { name: "Existing Client", exact: true })).toBeVisible()
  await expect(directPage.getByRole("link", { name: "Edit appointment", exact: true })).toBeVisible()
  await expect(directPage.locator("dialog")).toHaveCount(0)
  await context.close()
})
