const { test, expect } = require("./support/auth")

test("time grid aligns simultaneous bookings, scales duration, and keeps headers sticky", async ({ page }) => {
  await page.goto("/?view=day&date=2030-01-07")
  const viewport = page.locator(".calendar-viewport")
  const alex = page.locator(".appointment-card").filter({ hasText: "Existing Client" })
  const jamie = page.locator(".appointment-card").filter({ hasText: "Parallel Client" })
  const first = await alex.boundingBox()
  const second = await jamie.boundingBox()
  expect(Math.abs(first.y - second.y)).toBeLessThan(1)
  expect(second.x).toBeGreaterThan(first.x + first.width)
  expect(second.height).toBeCloseTo(first.height * 2, 0)
  await expect(page.locator(".break-block")).toContainText("Break")
  await expect(page.getByRole("link", { name: "Book Alex, January 7 at 12:00 PM, 60 minutes", exact: true })).toHaveCount(0)

  const headerY = (await page.locator(".time-grid-header").boundingBox()).y
  await viewport.evaluate(element => { element.scrollTop = 300 })
  expect((await page.locator(".time-grid-header").boundingBox()).y).toBeCloseTo(headerY, 0)
  expect((await viewport.boundingBox()).height).toBeLessThan(800)
  await page.getByRole("link", { name: "Week", exact: true }).click()
  await expect(page.locator(".day-column")).toHaveCount(7)
  await expect(page.locator(".stylist-lane")).toHaveCount(14)
  await page.getByRole("link", { name: "Alex", exact: true }).click()
  await expect(page.locator(".stylist-lane")).toHaveCount(7)
  await expect(page.locator(".appointment-card")).toHaveCount(1)
  await page.getByRole("link", { name: "Next week", exact: true }).click()
  await expect(page).toHaveURL(/week=2030-01-14/)
  await expect(page.locator(".appointment-card")).toHaveCount(0)
})

test("open slots prefill date, time and stylist and preserve day view", async ({ page }) => {
  await page.goto("/?view=day&date=2030-01-07")
  await page.getByRole("link", { name: "Book Alex, January 7 at 11:00 AM, 60 minutes", exact: true }).click()
  await expect(page.getByLabel("Date & time")).toHaveValue("2030-01-07T11:00")
  await expect(page.getByLabel("Stylist", { exact: true }).locator("option:checked")).toHaveText("Alex")
  await expect(page.locator("#day_availability [role=status]")).toContainText("No booking conflicts")
  await page.getByRole("link", { name: "Back to the calendar" }).click()
  await expect(page).toHaveURL(/view=day/)
  await expect(page.locator(".day-column")).toHaveCount(1)
})

test("mobile defaults to day view but honors an explicit week selection", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/?date=2030-01-07")
  await expect(page).toHaveURL(/view=day/)
  await expect(page.locator(".day-column")).toHaveCount(1)
  await page.getByRole("link", { name: "Week", exact: true }).click()
  await expect(page.locator(".day-column")).toHaveCount(7)
  await expect(page).toHaveURL(/view=week/)
  const dimensions = await page.evaluate(() => ({ width: innerWidth, content: document.documentElement.scrollWidth }))
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width)
})
