const { test, expect } = require("./support/auth")

test("working hours, breaks, days off, booking contacts, and editing availability", async ({ page }) => {
  await page.goto("/stylists")
  await page.getByRole("link", { name: "Edit hours for Alex" }).click()
  const monday = page.getByRole("group", { name: "Monday", exact: true })
  await monday.getByLabel("Start", { exact: true }).fill("09:30")
  await monday.getByLabel("Finish", { exact: true }).fill("17:00")
  await monday.getByLabel("Break starts").fill("12:00")
  await monday.getByLabel("Break ends").fill("13:00")
  await page.getByRole("group", { name: "Tuesday", exact: true }).getByLabel("Day off").check()
  await page.getByRole("button", { name: "Save working hours" }).click()
  await expect(page.getByRole("status")).toContainText("Working hours saved")

  await page.goto("/appointments/new?date=2030-01-07")
  await page.getByLabel("Stylist", { exact: true }).selectOption({ label: "Alex" })
  const planner = page.locator("#day_availability")
  await expect(planner).toContainText("Working hours: 09:30–17:00")
  await expect(planner.getByRole("status")).toContainText("Outside working hours")
  await expect(planner.locator('[data-time="2030-01-07T09:30"]')).toHaveCount(0)
  await expect(planner.locator('[data-time="2030-01-07T12:00"]')).toHaveCount(0)
  await planner.getByRole("button", { name: "11:00 AM", exact: true }).click()
  await expect(page.getByLabel("Date & time")).toHaveValue("2030-01-07T11:00")
  await expect(planner.getByRole("status")).toContainText("No booking conflicts")

  await page.getByLabel("Or add a new client").fill("Morgan Browser")
  await page.getByLabel("New client email (optional)").fill("morgan@example.com")
  await page.getByLabel("New client phone (optional)").fill("+1 212 555 0123")
  await planner.getByRole("button", { name: "Next day" }).click()
  await expect(planner.getByRole("status")).toContainText("Day off")
  await expect(planner.locator(".time-slot")).toHaveCount(0)
  await expect(page.getByLabel("Or add a new client")).toHaveValue("Morgan Browser")
  await planner.getByRole("button", { name: "Previous day" }).click()
  await expect(planner.getByRole("status")).toContainText("No booking conflicts")
  await page.getByRole("button", { name: "Book appointment" }).click()
  await expect(page.locator(".appointment-card").filter({ hasText: "Morgan Browser" })).toBeVisible()
  await page.locator(".appointment-card").filter({ hasText: "Morgan Browser" }).click()
  await page.getByRole("dialog").getByRole("link", { name: "Edit appointment", exact: true }).click()
  await expect(planner.getByRole("status")).toContainText("No booking conflicts")
  await expect(planner.getByRole("button", { name: "11:00 AM", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.getByLabel("Date & time").fill("2030-01-07T12:00")
  await page.getByLabel("Date & time").press("Tab")
  await expect(planner.getByRole("status")).toContainText("During a break")
  await page.getByRole("button", { name: "Save changes" }).click()
  await expect(page.getByRole("alert")).toContainText("outside their break")
})

test("service defaults apply on change and preserve a saved custom duration", async ({ page }) => {
  await page.goto("/services")
  await page.getByRole("link", { name: "Edit Blowout", exact: true }).click()
  await page.getByLabel("Default duration").selectOption("45")
  await page.getByRole("button", { name: "Save service" }).click()
  await expect(page.getByRole("status")).toContainText("Service default updated")
  await page.goto("/appointments/new?date=2030-01-09")
  await page.getByLabel("Stylist", { exact: true }).selectOption({ label: "Jamie" })
  await page.getByLabel("Service", { exact: true }).selectOption("Blowout")
  await expect(page.getByLabel("Duration", { exact: true })).toHaveValue("45")
  await expect(page.locator("#day_availability")).toContainText("45 min")
  await page.getByLabel("Duration", { exact: true }).selectOption("90")
  await expect(page.locator("#day_availability")).toContainText("90 min")
  await page.getByLabel("Client", { exact: true }).selectOption({ label: "Existing Client · existing@example.com" })
  await page.getByRole("button", { name: "Book appointment" }).click()
  const card = page.locator(".appointment-card").filter({ hasText: "Blowout" })
  await expect(card).toContainText("90m")
  await card.click()
  await page.getByRole("dialog").getByRole("link", { name: "Edit appointment", exact: true }).click()
  await expect(page.getByLabel("Duration", { exact: true })).toHaveValue("90")
  await page.getByLabel("Service", { exact: true }).selectOption("Consultation")
  await expect(page.getByLabel("Duration", { exact: true })).toHaveValue("15")
})

test("client directory saves, searches and updates contact details on a narrow screen", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/clients/new")
  await page.getByLabel("Full name").fill("Casey Contact")
  await page.getByLabel("Email (optional)", { exact: true }).fill("CASEY@example.com")
  await page.getByLabel("Phone (optional)", { exact: true }).fill("+44 20 7946 0958")
  await page.getByLabel("Preferred stylist", { exact: true }).selectOption({ label: "Jamie" })
  await page.getByRole("button", { name: "Save client" }).click()
  await expect(page.getByRole("status")).toContainText("Client saved")
  await page.getByLabel("Search clients").fill("casey@example.com")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Casey Contact" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Existing Client" })).toHaveCount(0)
  await page.getByRole("link", { name: "Edit Casey Contact" }).click()
  await expect(page.getByLabel("Preferred stylist", { exact: true }).locator("option:checked")).toHaveText("Jamie")
  await page.getByLabel("Preferred stylist", { exact: true }).selectOption({ label: "No preference" })
  await page.getByLabel("Phone (optional)", { exact: true }).fill("+44 20 7946 0000")
  await page.getByRole("button", { name: "Save client" }).click()
  await expect(page.getByText("casey@example.com · +44 20 7946 0000", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Edit Casey Contact" }).click()
  await expect(page.getByLabel("Preferred stylist", { exact: true })).toHaveValue("")
})
