const { test, expect } = require("./support/auth")

test("team planner edits a single shift, protects bookings, and restores recurring hours", async ({ page }) => {
  await page.goto("/team_schedule?week=2030-01-07")
  await expect(page.getByRole("heading", { name: "The team schedule." })).toBeVisible()
  await expect(page.locator(".team-table tbody tr")).toHaveCount(2)
  await page.getByRole("link", { name: "Edit Alex shift on January 7", exact: true }).click()
  await page.getByLabel("Start", { exact: true }).fill("11:00")
  await page.getByRole("button", { name: "Save shift", exact: true }).click()
  await expect(page.getByRole("alert")).toContainText("conflicts")
  await expect(page.getByRole("link", { name: /Existing Client/ })).toBeVisible()
  await page.getByRole("link", { name: "Team schedule", exact: true }).first().click()

  await page.goto("/team_schedule?week=2030-02-04")
  await page.getByRole("link", { name: "Edit Jamie shift on February 4", exact: true }).click()
  await page.getByLabel("Start", { exact: true }).fill("11:00")
  await page.getByLabel("Finish", { exact: true }).fill("17:00")
  await page.getByLabel("Break starts").fill("13:00")
  await page.getByLabel("Break ends").fill("14:00")
  await page.getByRole("button", { name: "Save shift", exact: true }).click()
  const shift = page.getByRole("link", { name: "Edit Jamie shift on February 4", exact: true })
  await expect(shift).toContainText("One-day change")
  await expect(shift).toContainText("11:00–17:00")
  await page.goto("/appointments/new?date=2030-02-04")
  await page.getByLabel("Stylist", { exact: true }).selectOption({ label: "Jamie" })
  await expect(page.locator("#day_availability")).toContainText("Working hours: 11:00–17:00")
  await expect(page.locator("#day_availability [role=status]")).toContainText("Outside working hours")
  await page.goto("/team_schedule?week=2030-02-04")
  await shift.click()
  page.once("dialog", dialog => dialog.accept())
  await page.getByRole("button", { name: "Use recurring hours for this date" }).click()
  await expect(shift).toContainText("Usual hours")
  await expect(shift).toContainText("09:00–18:00")
})

test("team time off covers a date range and can be removed", async ({ page }) => {
  await page.goto("/time_offs/new?date=2030-02-05")
  await page.getByLabel("Team member").selectOption({ label: "Jamie" })
  await page.getByLabel("Last day off").fill("2030-02-07")
  await page.getByLabel("Note (optional)").fill("A few days away")
  await page.getByRole("button", { name: "Save time off" }).click()
  await expect(page.getByRole("link", { name: "Edit Jamie shift on February 5", exact: true })).toContainText("Time off")
  await expect(page.getByRole("link", { name: "Edit Jamie shift on February 7", exact: true })).toContainText("Time off")
  await expect(page.getByRole("link", { name: "Edit Jamie shift on February 8", exact: true })).toContainText("Usual hours")
  await page.goto("/appointments/new?date=2030-02-06")
  await page.getByLabel("Stylist", { exact: true }).selectOption({ label: "Jamie" })
  await expect(page.locator("#day_availability [role=status]")).toContainText("Time off")
  await expect(page.locator("#day_availability .time-slot")).toHaveCount(0)
  await page.goto("/team_schedule?week=2030-02-04")
  page.once("dialog", dialog => dialog.accept())
  await page.getByRole("button", { name: "Remove time off", exact: true }).click()
  await expect(page.getByRole("link", { name: "Edit Jamie shift on February 6", exact: true })).toContainText("Usual hours")
})
